### ISSUE TITLE
gridstack.js is included in the project as a static resource.

### ISSUE THREAD

**Issue by happtim** [itemzen/gridstack-blazor#2]
Blazor supports static resources. https://learn.microsoft.com/en-us/aspnet/core/blazor/fundamentals/static-files. 

Is it possible to simplify the installation method for gridstack.js, so that each version of Itemzen.GridStack.Blazor includes the corresponding version of gridstack.js by default? 

When referencing the corresponding resources, it can be done as follows: 
 `<script src="_content/Itemzen.GridStack.Blazor/gridstack-all.js"></script>`
`<link href="_content/Itemzen.GridStack.Blazor/gridstack.min.css" rel="stylesheet" />`
`<link href="_content/Itemzen.GridStack.Blazor/gridstack-extra.min.css" rel="stylesheet" />`

**Comment by vimception** [comment]
Hi @happtim, this was done on purpose so 1/ it is possible to update the gridstack version when an (important) bugfix is released without the need to wait for a new nuget package release and 2/ to decrease the maintenance burden on this library.

If you feel this is a useful addition, please feel free to open a PR each time a new version of gridstack is released.
